DROP DATABASE IF EXISTS SCAD;
CREATE DATABASE SCAD;
USE SCAD;
SET sql_mode = '';

DROP TABLE IF EXISTS SCAD_USER;

CREATE TABLE SCAD_USER
(
   ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
   FIRSTNAME varchar(100),
   LASTNAME varchar(100),
   EMAILADDRESS varchar(100),
   CONSTRAINT SCAD_USER_PK PRIMARY KEY(ID),
   CONSTRAINT SCAD_USER_UQ UNIQUE KEY(EMAILADDRESS)
);

INSERT INTO SCAD_USER 
(FIRSTNAME,LASTNAME,EMAILADDRESS) 
VALUES ('RK','KK','rk@my.ccsu.edu');
INSERT INTO SCAD_USER 
(FIRSTNAME,LASTNAME,EMAILADDRESS) 
VALUES ('PM','MM','pm@my.ccsu.edu');
INSERT INTO SCAD_USER 
(FIRSTNAME,LASTNAME,EMAILADDRESS) 
VALUES ('RL','LL','rl@my.ccsu.edu');
